{% set version = "0.1" %}
{% set commit = "b14771b6b6aa4429ca19c93aba8c315bf63ce227" %}

package:
  name: jsanimation
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/jakevdp/JSAnimation/archive/{{ commit }}.tar.gz
  sha256: 60be390282a76ef2681a11f29a4c4af57003c6bf81118dda9e512cce415761db

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib

test:
  imports:
    - JSAnimation

about:
  home: http://github.com/jakevdp/JSAnimation
  license: BSD 2-Clause
  summary: 'Javascript Animation exporter for matplotlib and IPython.'


extra:
  recipe-maintainers:
    - ocefpaf
    - rsignell-usgs
