{% set version = "0.1" %}
{% set commit = "d290db11ebb5427769b76fc532f2d10c4ea3391f" %}

package:
  name: jsanimation
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/jakevdp/JSAnimation/archive/{{ commit }}.tar.gz
  sha256: d09afaa47974410a2877995844626c9ed10d74e6ab934a92ec1c567364bb5b08

build:
  number: 3
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - JSAnimation

about:
  home: http://github.com/jakevdp/JSAnimation
  license: BSD2-Clause
  license_file: LICENSE
  summary: 'Javascript Animation exporter for matplotlib and IPython'


extra:
  recipe-maintainers:
    - ocefpaf
    - rsignell-usgs
