travis:
  secure:
    BINSTAR_TOKEN: nlB/jE1cX9brVb7HkDs5PO4i9goq706Enm4XQPV0QlSCIgkilngo7sRqAfE2By7B9x40lSdSkNESUEwaFvlKRyA5LcBp0/dQ0Yjtlln7oQ38uIX5ucdjcjrg5ZDnsrDyAS/RaO1TWIlBGv0MTxvM9vKxfHhAzYW51CC+e9bGWDQYKq1HinSauJh8qob2tFsk+CFQ/C3GghALWqSeJ6oWP815jIBw+k6trruSWD7o7pudLVuFV6LLJXtceRG5V0PtK2a70aO3qlsRuUN2zQWQRQRJ9qaHqOvgwMJOh9sKhtPopeh+ebwE95P7xz5QQAyTkOqvo4Rll5gWFG35rrkr1EI27R0NermwpTfvzuOAWGU1J7egimvAiN3GZxy1p6/HHtkUo5HzwLHU51iePQx8nXvftP4Ho8sLfRIGrisDAkHbEN1Bwh+hoYx8geevMM8/xv848Fm1mD4hONa8/ZhyhH8vYo4rpX7ePdSAonZbliMgS2J2Emq08g7mtQvLZZHfGPbofavPvgs1MAGB2LvXumfhQygSxgRgrZRlxyfHEKlMozQhPSbQXzesob8gzSqAU3xKCqvuy7taPPYo+kULOmwhRxToDNzyZiRRLOW+nyHFf+7lmlGaEhvxsbB39TDVuqQo8xM8uBAaQMfZGu4QAzQBDphrRJ0xgBAsZUzLM+U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
