travis:
  secure:
    BINSTAR_TOKEN: ISHRLZU7LcJX9bEHEAG9JEsnFhYcGr7etAGy89jchZ3ZBv1r+AGQXyaVnrgpzCNtiibg9XHthW9XiG52a4AyfePkv3LytaeOzf1Qv8fdsJLNt/LV0w9o41R9ARx7SwxlsHjwysodwEVEicJEDo8dY9MGpC7QHQJ5MtjpTMtagaptGkNK3NkygDyPJsisRxvywOFQK//AWsl9RXP91oGTgTMTmMhbymyZMu5TItV6h+opnA7GC3PviY7QRWK35m1oZnkI2pCOdvjPXAggx5zEHjRPRDIyARPSjoUcC4VclHJ/UU3RtqAkjENWhbQpgiMj8BAa6GknBeSb2ud+V+8n1783HNlVAC31xVezlFnx4xcqwudL2JwHKadf0yiYGBZyUil/9Z4D8riWJtZcEy//B0f3LzrFNg+pBrjphGy2khIwCKgfCxSvuKPnm2GU1wqcuHZYmgY21z3jq3/Cv+58k2aeCGjqUsWr1y8/91aAEuhPjTW5YJieyNtoeDzODcWewGdf3/9mJm3vdWZW8A8nrIilga+ZBDrI8PANauXsn+xLlQLaIIQ8qHmBokKlDfW654zr7TA0hPcZkcWBWJXZ7r5xWLq93ffBvvpCnFRJwYCR9hxeVTCgarf9fumsqQzT8RFSe0WbIxfIksWveFulGUmsnQD/S+ZXhxj/pEfFkTo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
